=== sdbs-uni-p/json-schema-containment-testsuite/test-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "description": "Schema for tests",
    "type": "array",
    "items": {
        "type": "object",
        "required": [ "id", "schema1", "schema2", "tests" ],
        "properties": {
            "id": {
                "description": "Uniquely identifies a set of tests within the same file",
                "type": "number"
            },
            "description": {
                "description": "The test set description",
                "type": "string"
            },
            "comment": {
                "description": "Any additional comments about the test set",
                "type": "string"
            },
            "schema1": {
                "description": "This should be a valid schema. This should be a ref to a meta-schema if schema keywords need testing. This is the first subschenma."
            },
            "schema2": {
                "description": "This should be a valid schema. This should be a ref to a meta-schema if schema keywords need testing. This is the second subschenma."
            },
            "tests": {
                "description": "A test for the relation of schema1 and schema2",
                "type": "object",
                "properties": { 
                    "s1SubsetEqOfs2": {
                        "type": "boolean"
                      },
                    "s2SubsetEqOfs1": {
                        "type": "boolean"
                      }
                },
                "additionalProperties": false,
                "required":["s1SubsetEqOfs2"]
            }
        },
        "additionalProperties": false
        
    },
    "minItems": 1
}

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft-future/nonvalid/defs.json
[
    {
        "id": 1,
        "schema1": {
            "const": {
                "$defs": {
                    "foo": {
                        "type": "integer"
                    }
                }
            }
        },
        "schema2": {
            "not": {
                "$ref": "https://json-schema.org/draft/future/schema"
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft-future/unions/maxContains.json
[
    {
        "id": 1,
        "schema1": {
            "anyOf": [
                {
                    "const": [
                        1
                    ]
                },
                {
                    "const": [
                        1,
                        2
                    ]
                },
                {
                    "const": {
                        "a": 1
                    }
                },
                {
                    "const": {
                        "a": 1,
                        "b": 2
                    }
                }
            ]
        },
        "schema2": {
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 2,
        "schema1": {
            "anyOf": [
                {
                    "const": [
                        1
                    ]
                },
                {
                    "const": [
                        1,
                        2
                    ]
                },
                {
                    "const": {
                        "a": 1
                    }
                },
                {
                    "const": {
                        "a": 1,
                        "b": 2
                    }
                }
            ]
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 3,
        "schema1": {
            "anyOf": [
                {
                    "const": [
                        1,
                        1
                    ]
                },
                {
                    "const": {
                        "a": 1,
                        "b": 1
                    }
                }
            ]
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "minContains": 1,
            "maxContains": 3
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft-future/valid/defs.json
[
    {
        "id": 1,
        "schema1": {
            "const": {
                "$defs": {
                    "foo": {
                        "type": "integer"
                    }
                }
            }
        },
        "schema2": {
            "$ref": "https://json-schema.org/draft/future/schema"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 2,
        "schema1": {
            "const": {
                "$defs": {
                    "foo": {
                        "type": 1
                    }
                }
            }
        },
        "schema2": {
            "$ref": "https://json-schema.org/draft/future/schema"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft7/valid/optional/format/relative-json-pointer.json
[
    {
        "id": 1,
        "schema1": {
            "const": "1"
        },
        "schema2": {
            "format": "relative-json-pointer"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 2,
        "schema1": {
            "const": "0/foo/bar"
        },
        "schema2": {
            "format": "relative-json-pointer"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 3,
        "schema1": {
            "const": "2/0/baz/1/zip"
        },
        "schema2": {
            "format": "relative-json-pointer"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 4,
        "schema1": {
            "const": "0#"
        },
        "schema2": {
            "format": "relative-json-pointer"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 5,
        "schema1": {
            "const": "/foo/bar"
        },
        "schema2": {
            "format": "relative-json-pointer"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 6,
        "schema1": {
            "const": "-1/foo/bar"
        },
        "schema2": {
            "format": "relative-json-pointer"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft-future/nonvalid/maxContains.json
[
    {
        "id": 1,
        "schema1": {
            "const": [
                1
            ]
        },
        "schema2": {
            "not": {
                "maxContains": 1
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 2,
        "schema1": {
            "const": [
                1,
                2
            ]
        },
        "schema2": {
            "not": {
                "maxContains": 1
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 3,
        "schema1": {
            "const": {
                "a": 1
            }
        },
        "schema2": {
            "not": {
                "maxContains": 1
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 4,
        "schema1": {
            "const": {
                "a": 1,
                "b": 2
            }
        },
        "schema2": {
            "not": {
                "maxContains": 1
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 5,
        "schema1": {
            "const": [
                1
            ]
        },
        "schema2": {
            "not": {
                "contains": {
                    "const": 1
                },
                "maxContains": 1
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 6,
        "schema1": {
            "const": [
                1,
                2
            ]
        },
        "schema2": {
            "not": {
                "contains": {
                    "const": 1
                },
                "maxContains": 1
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 7,
        "schema1": {
            "const": {
                "a": 1
            }
        },
        "schema2": {
            "not": {
                "contains": {
                    "const": 1
                },
                "maxContains": 1
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 8,
        "schema1": {
            "const": {
                "a": 1,
                "b": 2
            }
        },
        "schema2": {
            "not": {
                "contains": {
                    "const": 1
                },
                "maxContains": 1
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 9,
        "schema1": {
            "const": [
                1,
                1
            ]
        },
        "schema2": {
            "not": {
                "contains": {
                    "const": 1
                },
                "minContains": 1,
                "maxContains": 3
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 10,
        "schema1": {
            "const": {
                "a": 1,
                "b": 1
            }
        },
        "schema2": {
            "not": {
                "contains": {
                    "const": 1
                },
                "minContains": 1,
                "maxContains": 3
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft2020-12/valid/optional/format/time.json
[
    {
        "id": 1,
        "schema1": {
            "const": "08:30:06Z"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 2,
        "schema1": {
            "const": "23:59:60Z"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 3,
        "schema1": {
            "const": "15:59:60-08:00"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 4,
        "schema1": {
            "const": "23:20:50.52Z"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 5,
        "schema1": {
            "const": "08:30:06.283185Z"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 6,
        "schema1": {
            "const": "08:30:06+00:20"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 7,
        "schema1": {
            "const": "08:30:06-08:00"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 8,
        "schema1": {
            "const": "08:30:06z"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 9,
        "schema1": {
            "const": "24:00:00Z"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 10,
        "schema1": {
            "const": "00:60:00Z"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 11,
        "schema1": {
            "const": "00:00:61Z"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 12,
        "schema1": {
            "const": "22:59:60Z"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 13,
        "schema1": {
            "const": "23:58:60Z"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 14,
        "schema1": {
            "const": "01:02:03+24:00"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 15,
        "schema1": {
            "const": "01:02:03+00:60"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 16,
        "schema1": {
            "const": "01:02:03Z+00:30"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 17,
        "schema1": {
            "const": "08:30:06 PST"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 18,
        "schema1": {
            "const": "01:01:01,1111"
        },
        "schema2": {
            "format": "time"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    }
]
