=== sdbs-uni-p/json-schema-containment-testsuite/test-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "description": "Schema for tests",
    "type": "array",
    "items": {
        "type": "object",
        "required": [ "id", "schema1", "schema2", "tests" ],
        "properties": {
            "id": {
                "description": "Uniquely identifies a set of tests within the same file",
                "type": "number"
            },
            "description": {
                "description": "The test set description",
                "type": "string"
            },
            "comment": {
                "description": "Any additional comments about the test set",
                "type": "string"
            },
            "schema1": {
                "description": "This should be a valid schema. This should be a ref to a meta-schema if schema keywords need testing. This is the first subschenma."
            },
            "schema2": {
                "description": "This should be a valid schema. This should be a ref to a meta-schema if schema keywords need testing. This is the second subschenma."
            },
            "tests": {
                "description": "A test for the relation of schema1 and schema2",
                "type": "object",
                "properties": { 
                    "s1SubsetEqOfs2": {
                        "type": "boolean"
                      },
                    "s2SubsetEqOfs1": {
                        "type": "boolean"
                      }
                },
                "additionalProperties": false,
                "required":["s1SubsetEqOfs2"]
            }
        },
        "additionalProperties": false
        
    },
    "minItems": 1
}

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft3/valid/optional/format/date.json
[
    {
        "id": 1,
        "schema1": {
            "const": "1963-06-19"
        },
        "schema2": {
            "format": "date"
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 2,
        "schema1": {
            "const": "06/19/1963"
        },
        "schema2": {
            "format": "date"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 3,
        "schema1": {
            "const": "2013-350"
        },
        "schema2": {
            "format": "date"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 4,
        "schema1": {
            "const": "1998-1-20"
        },
        "schema2": {
            "format": "date"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 5,
        "schema1": {
            "const": "1998-01-1"
        },
        "schema2": {
            "format": "date"
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft-future/reflexive/defs.json
[
    {
        "id": 1,
        "schema1": {
            "$ref": "https://json-schema.org/draft/future/schema"
        },
        "schema2": {
            "$ref": "https://json-schema.org/draft/future/schema"
        },
        "tests": {
            "s1SubsetEqOfs2": true,
            "s2SubsetEqOfs1": true
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft-future/universal/defs.json
[
    {
        "id": 1,
        "schema1": {
            "anyOf": [
                {
                    "$ref": "https://json-schema.org/draft/future/schema"
                },
                {
                    "not": {
                        "$ref": "https://json-schema.org/draft/future/schema"
                    }
                }
            ]
        },
        "schema2": true,
        "tests": {
            "s1SubsetEqOfs2": true,
            "s2SubsetEqOfs1": true
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft-future/unions/contains.json
[
    {
        "id": 1,
        "schema1": {
            "anyOf": [
                {
                    "const": [
                        3,
                        4,
                        5
                    ]
                },
                {
                    "const": [
                        3,
                        4,
                        6
                    ]
                },
                {
                    "const": [
                        3,
                        4,
                        5,
                        6
                    ]
                },
                {
                    "const": {
                        "a": 3,
                        "b": 4,
                        "c": 5
                    }
                },
                {
                    "const": {
                        "a": 3,
                        "b": 4,
                        "c": 6
                    }
                },
                {
                    "const": {
                        "a": 3,
                        "b": 4,
                        "c": 5,
                        "d": 6
                    }
                },
                {
                    "const": 42
                }
            ]
        },
        "schema2": {
            "contains": {
                "minimum": 5
            }
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 2,
        "schema1": {
            "anyOf": [
                {
                    "const": [
                        3,
                        4,
                        5
                    ]
                },
                {
                    "const": [
                        3,
                        4,
                        5,
                        5
                    ]
                },
                {
                    "const": {
                        "a": 3,
                        "b": 4,
                        "c": 5
                    }
                },
                {
                    "const": {
                        "a": 3,
                        "b": 4,
                        "c": 5,
                        "d": 5
                    }
                }
            ]
        },
        "schema2": {
            "contains": {
                "const": 5
            }
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 3,
        "schema1": {
            "anyOf": [
                {
                    "const": [
                        "foo"
                    ]
                },
                {
                    "const": {
                        "a": "foo"
                    }
                }
            ]
        },
        "schema2": {
            "contains": true
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 4,
        "schema1": {
            "anyOf": [
                {
                    "const": [
                        6,
                        12
                    ]
                },
                {
                    "const": {
                        "a": 6,
                        "b": 12
                    }
                }
            ]
        },
        "schema2": {
            "additionalProperties": {
                "multipleOf": 2
            },
            "items": {
                "multipleOf": 2
            },
            "contains": {
                "multipleOf": 3
            }
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 5,
        "schema1": {
            "anyOf": [
                {
                    "const": [
                        "foo"
                    ]
                },
                {
                    "const": {
                        "a": "foo"
                    }
                }
            ]
        },
        "schema2": {
            "contains": {
                "if": false,
                "else": true
            }
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft-future/nonvalid/contains.json
[
    {
        "id": 1,
        "schema1": {
            "const": [
                3,
                4,
                5
            ]
        },
        "schema2": {
            "not": {
                "contains": {
                    "minimum": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 2,
        "schema1": {
            "const": [
                3,
                4,
                6
            ]
        },
        "schema2": {
            "not": {
                "contains": {
                    "minimum": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 3,
        "schema1": {
            "const": [
                3,
                4,
                5,
                6
            ]
        },
        "schema2": {
            "not": {
                "contains": {
                    "minimum": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 4,
        "schema1": {
            "const": {
                "a": 3,
                "b": 4,
                "c": 5
            }
        },
        "schema2": {
            "not": {
                "contains": {
                    "minimum": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 5,
        "schema1": {
            "const": {
                "a": 3,
                "b": 4,
                "c": 6
            }
        },
        "schema2": {
            "not": {
                "contains": {
                    "minimum": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 6,
        "schema1": {
            "const": {
                "a": 3,
                "b": 4,
                "c": 5,
                "d": 6
            }
        },
        "schema2": {
            "not": {
                "contains": {
                    "minimum": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 7,
        "schema1": {
            "const": 42
        },
        "schema2": {
            "not": {
                "contains": {
                    "minimum": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 8,
        "schema1": {
            "const": [
                3,
                4,
                5
            ]
        },
        "schema2": {
            "not": {
                "contains": {
                    "const": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 9,
        "schema1": {
            "const": [
                3,
                4,
                5,
                5
            ]
        },
        "schema2": {
            "not": {
                "contains": {
                    "const": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 10,
        "schema1": {
            "const": {
                "a": 3,
                "b": 4,
                "c": 5
            }
        },
        "schema2": {
            "not": {
                "contains": {
                    "const": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 11,
        "schema1": {
            "const": {
                "a": 3,
                "b": 4,
                "c": 5,
                "d": 5
            }
        },
        "schema2": {
            "not": {
                "contains": {
                    "const": 5
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 12,
        "schema1": {
            "const": [
                "foo"
            ]
        },
        "schema2": {
            "not": {
                "contains": true
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 13,
        "schema1": {
            "const": {
                "a": "foo"
            }
        },
        "schema2": {
            "not": {
                "contains": true
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 14,
        "schema1": {
            "const": "contains does not apply to strings"
        },
        "schema2": {
            "not": {
                "contains": false
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 15,
        "schema1": {
            "const": [
                6,
                12
            ]
        },
        "schema2": {
            "not": {
                "additionalProperties": {
                    "multipleOf": 2
                },
                "items": {
                    "multipleOf": 2
                },
                "contains": {
                    "multipleOf": 3
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 16,
        "schema1": {
            "const": {
                "a": 6,
                "b": 12
            }
        },
        "schema2": {
            "not": {
                "additionalProperties": {
                    "multipleOf": 2
                },
                "items": {
                    "multipleOf": 2
                },
                "contains": {
                    "multipleOf": 3
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 17,
        "schema1": {
            "const": [
                "foo"
            ]
        },
        "schema2": {
            "not": {
                "contains": {
                    "if": false,
                    "else": true
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 18,
        "schema1": {
            "const": {
                "a": "foo"
            }
        },
        "schema2": {
            "not": {
                "contains": {
                    "if": false,
                    "else": true
                }
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft-future/unsatisfiable/defs.json
[
    {
        "id": 1,
        "schema1": {
            "allOf": [
                {
                    "$ref": "https://json-schema.org/draft/future/schema"
                },
                {
                    "not": {
                        "$ref": "https://json-schema.org/draft/future/schema"
                    }
                }
            ]
        },
        "schema2": false,
        "tests": {
            "s1SubsetEqOfs2": true,
            "s2SubsetEqOfs1": true
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft2019-09/nonvalid/optional/format/time.json
[
    {
        "id": 1,
        "schema1": {
            "const": "08:30:06Z"
        },
        "schema2": {
            "not": {
                "format": "time"
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 2,
        "schema1": {
            "const": "23:59:60Z"
        },
        "schema2": {
            "not": {
                "format": "time"
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 3,
        "schema1": {
            "const": "15:59:60-08:00"
        },
        "schema2": {
            "not": {
                "format": "time"
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 4,
        "schema1": {
            "const": "23:20:50.52Z"
        },
        "schema2": {
            "not": {
                "format": "time"
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 5,
        "schema1": {
            "const": "08:30:06.283185Z"
        },
        "schema2": {
            "not": {
                "format": "time"
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 6,
        "schema1": {
            "const": "08:30:06+00:20"
        },
        "schema2": {
            "not": {
                "format": "time"
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 7,
        "schema1": {
            "const": "08:30:06-08:00"
        },
        "schema2": {
            "not": {
                "format": "time"
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 8,
        "schema1": {
            "const": "08:30:06z"
        },
        "schema2": {
            "not": {
                "format": "time"
            }
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    }
]

=== sdbs-uni-p/json-schema-containment-testsuite/tests/draft-future/valid/maxContains.json
[
    {
        "id": 1,
        "schema1": {
            "const": [
                1
            ]
        },
        "schema2": {
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 2,
        "schema1": {
            "const": [
                1,
                2
            ]
        },
        "schema2": {
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 3,
        "schema1": {
            "const": {
                "a": 1
            }
        },
        "schema2": {
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 4,
        "schema1": {
            "const": {
                "a": 1,
                "b": 2
            }
        },
        "schema2": {
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 5,
        "schema1": {
            "const": []
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 6,
        "schema1": {
            "const": [
                1
            ]
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 7,
        "schema1": {
            "const": [
                1,
                1
            ]
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 8,
        "schema1": {
            "const": [
                1,
                2
            ]
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 9,
        "schema1": {
            "const": [
                1,
                2,
                1
            ]
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 10,
        "schema1": {
            "const": {}
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 11,
        "schema1": {
            "const": {
                "a": 1
            }
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 12,
        "schema1": {
            "const": {
                "a": 1,
                "b": 1
            }
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 13,
        "schema1": {
            "const": {
                "a": 1,
                "b": 2
            }
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 14,
        "schema1": {
            "const": {
                "a": 1,
                "b": 2,
                "c": 1
            }
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "maxContains": 1
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 15,
        "schema1": {
            "const": []
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "minContains": 1,
            "maxContains": 3
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 16,
        "schema1": {
            "const": [
                1,
                1
            ]
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "minContains": 1,
            "maxContains": 3
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 17,
        "schema1": {
            "const": [
                1,
                1,
                1,
                1
            ]
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "minContains": 1,
            "maxContains": 3
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 18,
        "schema1": {
            "const": {}
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "minContains": 1,
            "maxContains": 3
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    },
    {
        "id": 19,
        "schema1": {
            "const": {
                "a": 1,
                "b": 1
            }
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "minContains": 1,
            "maxContains": 3
        },
        "tests": {
            "s1SubsetEqOfs2": true
        }
    },
    {
        "id": 20,
        "schema1": {
            "const": {
                "a": 1,
                "b": 1,
                "c": 1,
                "d": 1
            }
        },
        "schema2": {
            "contains": {
                "const": 1
            },
            "minContains": 1,
            "maxContains": 3
        },
        "tests": {
            "s1SubsetEqOfs2": false
        }
    }
]
